### PR TITLE
Unit tests with mocks, single responsibility services and interfaces

### PR DESCRIPTION
**Pull request by sdesyllas**
General improvements including:

- Unit tests mocking out the dependencies of the main service
- Separated functionality in different interfaces
- General code improvements

### CODE REVIEW

**Comment by richorama** [comment]
Thanks. I’ll take a look at this at the end of next week when I’m in front of a computer.

**Comment by sdesyllas** [comment]
Hi Richard thanks!

Basically the biggest change is that I used interfaces for JsonParser and
Fileloader so that the Lookup service can be easily unit tested while
mocking out jsonparser and file loader, these interfaces are now injected
from  the constructor of the lookup service. The service also now
implements an interface so that can be used with dependency injection in
other applications. Some improvements in naming conventions and coding
sugar added as well. The solution cannot be built from appveyor continues
integration though, you may have to use latest version of the ms build
agent.

**Comment by sdesyllas** [comment]
Also I replaced Microsoft test framework with xunit with fluent assertions for more intuitive tests.

**Comment by richorama** [comment]
Thank you for your contribution!

**Pull request merged**
